import type { Metadata } from "next";
import Link from "next/link";
import Nav from "./(components)/nav";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { FaInstagram, FaFacebook } from "react-icons/fa";
import { ClerkProvider } from "@clerk/nextjs";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning className="scroll-smooth">
        <body> 
          
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Nav />
             {children}
            <footer className="w-full bg-slate-950 text-slate-400 border-t border-slate-900 mt-28">
              <div className="mx-auto w-[90%] max-w-6xl py-12 sm:py-16 flex flex-col md:flex-row justify-between items-center md:items-start gap-8 md:gap-12 text-center md:text-left">
                {/* Left side: branding & copyright */}
                <div className="space-y-3">
                  <h3 className="font-semibold text-white tracking-tight text-lg">
                    Júlia Language Tutoring
                  </h3>
                  <p className="text-xs text-slate-500">
                    Júlia Language Tutoring © 2026. All rights reserved.
                  </p>
                </div>
                
                {/* Right side: links */}
                <div className="flex flex-row items-start gap-12 sm:gap-16">
                  {/* Follow us section */}
                  <div className="space-y-3">
                    <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-200">
                      Follow Us
                    </h4>
                    <div className="flex flex-row justify-center md:justify-start items-center gap-4">
                      <a 
                        href="https://www.instagram.com/saileach.gan.teorainn/" 
                        target="_blank" 
                        rel="noopener noreferrer"
                        className="text-slate-400 hover:text-pink-500 transition-colors duration-200"
                      >
                        <FaInstagram className="text-xl" />
                      </a>
                      <a 
                        href="#" 
                        className="text-slate-400 hover:text-blue-500 transition-colors duration-200"
                      >
                        <FaFacebook className="text-xl" />
                      </a>
                    </div>
                  </div>

                  {/* Legal section */}
                  <div className="space-y-3">
                    <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-200">
                      Legal
                    </h4>
                    <div className="space-y-2 text-sm">
                      <a 
                        href="#" 
                        className="block text-slate-400 hover:text-white transition-colors duration-200"
                      >
                        Privacy Policy
                      </a>
                      <a 
                        href="#" 
                        className="block text-slate-400 hover:text-white transition-colors duration-200"
                      >
                        Terms and Conditions
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </footer>
          </ThemeProvider>          
        </body>
    </html>
    </ClerkProvider>
  );
}
